Lien = require('./classes/lien.js')

Parse.Cloud.define 'hello', (request, response) ->
  response.success 'Hello world!'
  return

Parse.Cloud.beforeSave 'Lien', (request, response) ->
  if request.object.isNew()
    query = new (Parse.Query)('Lien')
    query.equalTo 'unique_id', request.object.get('unique_id')
    query.find().then( (liens) ->
      if liens.length == 0
        response.success()
      else
        response.error("Lien already created with this unique_id")
    )
  else
    response.success()
  return

Parse.Cloud.beforeSave 'LienSub', (request, response) ->
  if request.object.isNew()
    query = new (Parse.Query)('Lien')
    query.equalTo 'type', request.object.get('type')
    query.equalTo 'sub_date', request.object.get('sub_date')
    query.find().then( (liens) ->
      if liens.length == 0
        response.success()
      else
        response.error("LienSub already created with this unique_id")
    )
  else
    response.success()
  return
# ---
# generated by js2coffee 2.1.0
